#!/usr/bin/env sh

genImports () {
  local imports=$(find . -type f -not -name '*imports.nix' | sed 's/^/    /')
  echo "$imports"
  echo "{ ... }:

{
  imports = [
$imports
  ];
}" > imports.nix
}
if u="$(git ls-files --exclude-standard --others)" && test -z "$u"; then
  echo "git is dirty, exiting";
  exit 1;
fi
echo "Generating modules/nixos/imports.nix:"
cd $HOME/.config/nixos/modules/nixos
genImports
git add imports.nix
echo "Generating modules/home-manager/imports.nix:"
cd $HOME/.config/nixos/modules/home-manager
genImports
git add imports.nix
#git commit -m "AUTO: Generated imports.nix"
#git push
